'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('product', [
      {
        id: 1,
        code: 'P001',
        name: 'KENZIE PAINT NC SAVER DIAMOND WHITE',
        type_id: 1, 
        unit_id: 1, 
        unit_size_id: 1, 
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        code: 'P002',
        name: 'KENZIE PAINT NC SAVER DIAMOND BLACK',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        code: 'P003',
        name: 'KENZIE PAINT NC SAVER BLACKDOFF',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        code: 'P004',
        name: 'KENZIE PAINT NC SAVER WHITEDOFF',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        code: 'P005',
        name: 'KENZIE PAINT NC SAVER ORANGE YELLOW',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 6,
        code: 'P006',
        name: 'KENZIE PAINT NC SAVER LEMON YELLOW',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 7,
        code: 'P007',
        name: 'KENZIE PAINT NC SAVER SILVERSILK',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        code: 'P008',
        name: 'KENZIE PAINT NC SAVER RED TT',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 9,
        code: 'P009',
        name: 'KENZIE PAINT NC SAVER INTERNATIONAL ORANGE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 10,
        code: 'P010',
        name: 'KENZIE PAINT NC SAVER MENI WHITE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 11,
        code: 'P011',
        name: 'KENZIE PAINT NC SAVER GREEN',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 12,
        code: 'P012',
        name: 'KENZIE PAINT NC SAVER ROCK SILVER',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 13,
        code: 'P013',
        name: 'KENZIE PAINT NC SAVER CLEARGLOSS',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 14,
        code: 'P014',
        name: 'KENZIE PAINT NC SAVER BLUE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 15,
        code: 'P015',
        name: 'KENZIE PAINT NC SAVER MENI WHITE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 16,
        code: 'P016',
        name: 'KENZIE PAINT NC SAVER MENI GREY',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // NC ECO Products
      {
        id: 17,
        code: 'P017',
        name: 'KENZIE PAINT NC ECO DIAMOND WHITE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 18,
        code: 'P018',
        name: 'KENZIE PAINT NC ECO DIAMOND BLACK',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 19,
        code: 'P019',
        name: 'KENZIE PAINT NC ECO BLACKDOFF',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 20,
        code: 'P020',
        name: 'KENZIE PAINT NC ECO WHITEDOFF',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 21,
        code: 'P021',
        name: 'KENZIE PAINT NC ECO ORANGE YELLOW',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 22,
        code: 'P022',
        name: 'KENZIE PAINT NC ECO LEMON YELLOW',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 23,
        code: 'P023',
        name: 'KENZIE PAINT NC ECO SILVERSILK',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 24,
        code: 'P024',
        name: 'KENZIE PAINT NC ECO RED TT',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 25,
        code: 'P025',
        name: 'KENZIE PAINT NC ECO INTERNATIONAL ORANGE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 26,
        code: 'P026',
        name: 'KENZIE PAINT NC ECO MENI WHITE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 27,
        code: 'P027',
        name: 'KENZIE PAINT NC ECO GREEN',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 28,
        code: 'P028',
        name: 'KENZIE PAINT NC ECO BLUE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 29,
        code: 'P029',
        name: 'KENZIE PAINT NC ECO CLEARGLOSS',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 30,
        code: 'P030',
        name: 'KENZIE PAINT NC ECO MENI BLACK',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // NC PREMIO Products
      {
        id: 31,
        code: 'P031',
        name: 'KENZIE PAINT NC PREMIO INTERNATIONAL ORANGE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 32,
        code: 'P032',
        name: 'KENZIE PAINT NC PREMIO DIAMOND BLACK',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 33,
        code: 'P033',
        name: 'KENZIE PAINT NC PREMIO DIAMOND WHITE',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 34,
        code: 'P034',
        name: 'KENZIE PAINT NC PREMIO WHITEDOFF',
        type_id: 1,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // SYNTETIC SAVER Products
      {
        id: 35,
        code: 'P035',
        name: 'KENZIE PAINT SYNTETIC SAVER DIAMOND BLACK',
        type_id: 2, // SYNTETIC
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 36,
        code: 'P036',
        name: 'KENZIE PAINT SYNTETIC SAVER LEMON YELLOW',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 37,
        code: 'P037',
        name: 'KENZIE PAINT SYNTETIC SAVER SILVERSILK',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 38,
        code: 'P038',
        name: 'KENZIE PAINT SYNTETIC SAVER GREEN',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 39,
        code: 'P039',
        name: 'KENZIE PAINT SYNTETIC SAVER DIAMOND WHITE',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 40,
        code: 'P040',
        name: 'KENZIE PAINT SYNTETIC SAVER BLACKDOFF',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 41,
        code: 'P041',
        name: 'KENZIE PAINT SYNTETIC SAVER ORANGE YELLOW',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 42,
        code: 'P042',
        name: 'KENZIE PAINT SYNTETIC SAVER RED TT',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 43,
        code: 'P043',
        name: 'KENZIE PAINT SYNTETIC SAVER BLUE',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 44,
        code: 'P044',
        name: 'KENZIE PAINT SYNTETIC SAVER RED TT',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 45,
        code: 'P045',
        name: 'KENZIE PAINT SYNTETIC SAVER WHITEDOFF',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // SYNTETIC ECO Products
      {
        id: 46,
        code: 'P046',
        name: 'KENZIE PAINT SYNTETIC ECO DIAMOND BLACK',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 47,
        code: 'P047',
        name: 'KENZIE PAINT SYNTETIC ECO DIAMOND WHITE',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 48,
        code: 'P048',
        name: 'KENZIE PAINT SYNTETIC ECO BLUE',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 49,
        code: 'P049',
        name: 'KENZIE PAINT SYNTETIC ECO WHITE DOFF',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 50,
        code: 'P050',
        name: 'KENZIE PAINT SYNTETIC ECO RED TT',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 51,
        code: 'P051',
        name: 'KENZIE PAINT SYNTETIC ECO BLACK DOFF',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 52,
        code: 'P052',
        name: 'KENZIE PAINT SYNTETIC ECO GREEN',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 53,
        code: 'P053',
        name: 'KENZIE PAINT SYNTETIC ECO LEMON YELLOW',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 54,
        code: 'P054',
        name: 'KENZIE PAINT SYNTETIC ECO ORANGE YELLOW',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 55,
        code: 'P055',
        name: 'KENZIE PAINT SYNTETIC ECO INTERNATIONAL ORANGE',
        type_id: 2,
        unit_id: 1,
        unit_size_id: 1,
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // CLEAR BLINKZZ Products
      {
        id: 56,
        code: 'P056',
        name: 'BLINKZZ CLEAR COAT',
        type_id: 3, // CLEAR
        unit_id: 3, // LITRE
        unit_size_id: 3, // 0.8 L
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 57,
        code: 'P057',
        name: 'BLINKZZ CLEAR COAT',
        type_id: 3,
        unit_id: 3,
        unit_size_id: 6, // 200 ML
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 58,
        code: 'P058',
        name: 'BLINKZZ CLEAR COAT',
        type_id: 3,
        unit_id: 2,
        unit_size_id: 4, // 1 L
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 59,
        code: 'P059',
        name: 'BLINKZZ HARDENER',
        type_id: 3,
        unit_id: 3,
        unit_size_id: 6, // 200 ML
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 60,
        code: 'P060',
        name: 'BLINKZZ HARDENER',
        type_id: 3,
        unit_id: 3,
        unit_size_id: 6, // 0.2 L
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 61,
        code: 'P061',
        name: 'BLINKZZ HARDENER',
        type_id: 3,
        unit_id: 3,
        unit_size_id: 7, // 100 ML
        quantity: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('product', null, {});
  },
};
